### PR TITLE
[T-6596][17.0][ADD] reports_font_size: reimplementation of module

### PR DESCRIPTION
**Pull request by Tisho99**

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten

**Comment by Tisho99** [comment]
@ValentinVinagre I have agreed with Luis that it is not worth it adding all the header tag types because in almost all reports only h2 is used, and adding more header types will confuse the functional users

**Comment by Tisho99** [comment]
Tests need to be added

**Review by ValentinVinagre — CHANGES_REQUESTED** [review]
Add the commit history please, this module is not new.
Is a mig + ref .
add tests 😄

**Comment by ValentinVinagre** [comment]
> @ValentinVinagre I have agreed with Luis that it is not worth it adding all the header tag types because in almost all reports only h2 is used, and adding more header types will confuse the functional users

If it's generally sufficient, that's fine with me, and you can always expand it.

**Comment by Tisho99** [comment]
Haha the repo of the module was sy-server-backend

**Pull request closed without merging**
